kind: pipeline
name: default

steps:
- name: restore
  image: plugins/s3-cache
  settings:
    pull: true
    access_key: AKIA6DTKFYKBN7LY7GQ6
    secret_key: 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
    restore: true

- name: install
  image: node
  commands:
  - npm install

- name: rebuild
  image: plugins/s3-cache
  settings:
    pull: true
    access_key: AKIA6DTKFYKBN7LY7GQ6
    secret_key: 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
    rebuild: true
    mount:
      - node_modules
