kind: pipeline
name: default

steps:
- name: restore-cache
  image: meltwater/drone-cache:dev
  environment:
    AWS_ACCESS_KEY_ID: AKIA6DTKFYKBN7LY7GQ6
    AWS_SECRET_ACCESS_KEY: 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
  pull: true
  settings:
    restore: true
    bucket: dronereviewer
    region: ap-southeast-1
    cache_key: '{{ checksum "package.json" }}'
    archive_format: "gzip"
    mount:
      - 'node_modules'

- name: install
  image: node
  commands:
  - npm install

- name: rebuild-cache
  image: meltwater/drone-cache:dev
  pull: true
  environment:
    AWS_ACCESS_KEY_ID: AKIA6DTKFYKBN7LY7GQ6
    AWS_SECRET_ACCESS_KEY: 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
  settings:
    rebuild: true
    bucket: dronereviewer
    region: ap-southeast-1
    cache_key: '{{ checksum "package.json" }}'
    archive_format: "gzip"
    mount:
      - 'node_modules'
